# Generated by Django 6.0 on 2026-02-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='driver_id',
        ),
    ]
