# Generated by Django 6.0 on 2026-02-14 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_delivery_driver_id'),
        ('order', '0003_package_receiver_name_package_receiver_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='order.package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='package_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.package'),
        ),
    ]
