# Generated by Django 6.0 on 2026-02-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_order_id_remove_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
