# Generated by Django 6.0 on 2026-02-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_driverprofile_approval_status_and_more'),
        ('delivery', '0005_delivery_address_delivery_delivery_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='customer.driverprofile'),
        ),
    ]
