# Generated by Django 6.0 on 2026-02-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_delivery_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='assigned', max_length=20),
        ),
    ]
