# Generated by Django 6.0 on 2026-02-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_driverprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='phone',
        ),
    ]
