# Generated by Django 6.0 on 2026-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_driverprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
