# Generated by Django 6.0 on 2026-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customerprofile_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
