# Generated by Django 6.0 on 2026-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
