# Generated by Django 6.0 on 2026-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_emailotp_attempt_count_emailotp_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='otp_purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], default=False, max_length=20),
        ),
    ]
