# Generated by Django 6.0 on 2026-02-14 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerprofile_is_complete_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.driverprofile'),
        ),
        migrations.AlterField(
            model_name='package',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='order.order'),
        ),
    ]
