# Generated by Django 6.0 on 2026-02-14 10:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_driver_id_alter_package_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
