# Generated by Django 6.0 on 2026-02-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerprofile_is_complete_and_more'),
        ('order', '0005_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_id',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.driverprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
