# Generated by Django 6.0 on 2026-02-23 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_driverprofile_approval_status_and_more'),
        ('order', '0006_alter_order_driver_id_alter_order_pickup_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.driverprofile'),
        ),
    ]
