# Generated by Django 6.0 on 2026-02-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_driver_id_order_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='driver',
            new_name='driver_id',
        ),
    ]
