# Generated by Django 6.0 on 2026-02-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_driverprofile_approval_status_and_more'),
        ('order', '0008_rename_driver_order_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dorders', to='customer.driverprofile'),
        ),
    ]
