# Generated by Django 6.0 on 2026-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_id_alter_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
